### ISSUE TITLE
Replace bitanmi postgres with CNPG-Postgres Operator + Tenants

### ISSUE THREAD

**Issue by cloudymax** [small-hack/argocd-apps#270]
# Overview

Since we need to standardize MTLS, backups to S3, secrets and such across multiple postgres deployments it makes sense to use an operator/tenant model similar to how we use minio.

This ticket supersedes the following tasks:
- https://github.com/small-hack/argocd-apps/issues/124
- https://github.com/small-hack/argocd-apps/issues/123

This ticket overlaps with:
- https://github.com/small-hack/argocd-apps/issues/252

This ticket potentially resolves:
- https://github.com/small-hack/argocd-apps/issues/7

## Options

There are 3 major Postgres operators out there at the moment:
- Zolando
- CrunchyData
- CNPG. 

Of those I see that CNPG most closely shares our philosophy and architecture because CNPG provides support for: 
- Helm installation
- Ingress-Nginx
- Certmanager
- Monitoring via Grafana, Prometheus, and Alert Manager
- backups to Minio Gateway

They do not provide a tenant helm chart though.

##  Tasks
- [x] Create a basic tenant Helm chart - [HERE](https://github.com/small-hack/cnpg-tenant-chart)
- [x] Create ArgoCD appsets for Operator and Tenant
- [x] Add required options to Prometheus-Stack values.yaml to support monitoring and metrics
- [x] Add Grafana dashboard configmap to Prometheus-Stack appset
- [x] Add support to smol-k8s-lab for pre-generated minio secrets + buckets when postgres is used
- [x] Integrate with Mastodon
- [x] Integrate with Nextcloud
- [x] Integrate with Zitadel 
- [x] Integrate with Matrix
- [x] document and test postgres restore process
- [x] document the minor and major version upgrade process

---Optional---

- [ ] integrate with iceshrimp (maybe?)
- [ ] integrate with artifactory
- [ ] integrate with coturn

**Comment by cloudymax** [comment]
Opened a ticket with CNPG regarding TLS auth issues: https://github.com/cloudnative-pg/cloudnative-pg/issues/3301

**Comment by jessebot** [comment]
backup and restore process documented here: https://github.com/small-hack/argocd-apps/tree/main/postgres/operators/cloud-native-postgres/backups

**Comment by cloudymax** [comment]
will be resolved with: https://github.com/small-hack/argocd-apps/pull/536
